//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departments()
        {
            this.Opinion = new HashSet<Opinion>();
        }
    
        public int DepartmentId { get; set; }
        public int HospitalId { get; set; }
        public Nullable<int> DepartmentTypeId { get; set; }
        public string FullName { get; set; }
        public string DepartmentUrl { get; set; }
        public string DepartmentManagerName { get; set; }
        public bool IsConfirmed { get; set; }
        public string VisitTime { get; set; }
        public bool IsDeleted { get; set; }
        public string Tel { get; set; }
    
        public virtual DepartmentType DepartmentType { get; set; }
        public virtual Hospitals Hospitals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinion { get; set; }
    }
}
