//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int OpinionId { get; set; }
        public int UserId { get; set; }
        public int DepartmentId { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public int Rating1GeneralSatisfaction { get; set; }
        public int Rating2ListenAndRelate { get; set; }
        public int Rating3GettingHelpEasily { get; set; }
        public int Rating4SharingInformation { get; set; }
        public int Rating5AnEfficientProcess { get; set; }
        public int Rating6ConditionsOfHospitalization { get; set; }
        public int Rating7PreventionOfMedicalErrors { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<int> TotalRating { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Users Users { get; set; }
    }
}
